# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56f124c75be6828340e099348345a7399a110f0fbac9ae0fde8d12d646a9a684449f73d1b52cfc738047053e1e22c0da9e4564c7563278b7feea605a79580028

test:
  secret_key_base: e9e89e853944c74df1be8fc9c2200fd3fcc4b7b6c1d3a73d04c0b19b83f08beac2b12e2a18dbd630e084c348ea061bc01476f7ed252b54daedfc45c110edf7ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
